### PR TITLE
Task/add fantom

### PR DESCRIPTION
**Pull request by Tritium-VLK**
Not yet working, trying to add fantom chain.

### CODE REVIEW

**Comment by hammeiam** [comment]
Are you experiencing the same CORS issue as mentioned [here](https://github.com/Soptq/gnosis-safe-delegate-dapp/pull/5)?

**Comment by Soptq** [comment]
> Are you experiencing the same CORS issue as mentioned [here](https://github.com/Soptq/gnosis-safe-delegate-dapp/pull/5)?

Hi @hammeiam , yes I can confirm CORS issues with fantom safe API endpoint.

I tested its API endpoint using [Hoppscotch](https://hoppscotch.io/) and it fails as well, and therefore I think it is most likely a problem on fantom foundation site (as #5 mentioned fantom safe is maintained by fantom foundation instead of gnosis).

sc

As it can be seen on the attached screenshot, the `Access-Control-Allow-Origin` header is set twice, resulting in a CORS error. I will try contacting fantom foundation for help, for now you can setup a proxy server to proxy fantom api endpoint (https://safe.fantom.network) and drop the `Access-Control-Allow-Origin` field in the response header.

**Comment by hammeiam** [comment]
FYI this should be working now https://github.com/Soptq/gnosis-safe-delegate-dapp/pull/5#issuecomment-1069567141

**Comment by hammeiam** [comment]
@Soptq could we land this? The cors issue has been resolved

**Comment by Soptq** [comment]
> @Soptq could we land this? The cors issue has been resolved

sure 😄

**Pull request merged**
