### PR TITLE
feat: fantom support

### PR DESCRIPTION
**Pull request by kx9x**
https://safe.fantom.network/ seems to always return a CORS error if I don't use a proxy:
The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

Wasn't sure how to get past this without using a proxy, but will take suggestions

### CODE REVIEW

**Comment by kx9x** [comment]
hmm, this doesn't work in production, only locally. This is my first time dealing with CORS stuff, so I am a little lost.

**Comment by Soptq** [comment]
I see, I am not quite sure about it either, I used to confirmed with gnosis devs that all safe endpoints are deployed the same. Will definitely look into it later. For now, you can, as you said, setup a proxy server as a workaround. Thanks for your PR :)

**Comment by kx9x** [comment]
> I see, I am not quite sure about it either, I used to confirmed with gnosis devs that all safe endpoints are deployed the same. Will definitely look into it later. For now, you can, as you said, setup a proxy server as a workaround. Thanks for your PR :)

No problem! Unfortunately, the fantom safe isn't officially hosted by gnosis, it is self-hosted by the fantom foundation which makes differences like these very common :(

**Comment by hammeiam** [comment]
Hi @Soptq, any progress on this? Could we try to bring in someone from gnosis to change something on their end?

**Comment by HonzaDajc** [comment]
Hi @kx9x and @Soptq , what kind of request are you trying to do? I've tried for example https://safe.fantom.network/v1/chains/250/safes/0xDd4B0116498135ad965Bf289D06B8DaD6AF9a998/transactions/history
and got only one access-control-allow-origin in response header in chrome browser:

HTTP/1.1 200 OK
Server: nginx/1.20.1
Date: Mon, 14 Mar 2022 16:16:02 GMT
Content-Type: application/json
Content-Length: 5191
Connection: keep-alive
x-frame-options: SAMEORIGIN
x-content-type-options: nosniff
permissions-policy: interest-cohort=()
access-control-allow-origin: *
access-control-allow-methods: POST, GET, OPTIONS
access-control-allow-headers: X-Requested-With, Content-Type, Authorization
access-control-allow-credentials: true

**Comment by Soptq** [comment]
Hi @HonzaDajc , could you please test this URL: https://safe.fantom.network/api/v1/owners/0xDd4B0116498135ad965Bf289D06B8DaD6AF9a998/safes

I tested it using https://hoppscotch.io/ and it fails as well due to two `access-control-allow-origin`

**Comment by HonzaDajc** [comment]
Hi @Soptq, I've changed headers according to Gnosis and it is now working in hoppscotch.io

**Comment by jorijnsmit** [comment]
@Soptq what is still needed now to get support for ftm?

**Comment by Soptq** [comment]
> @Soptq what is still needed now to get support for ftm?

It should already supports ftm as https://github.com/Soptq/gnosis-safe-delegate-dapp/pull/6 is merged.

**Comment by poolpitako** [comment]
FTM is still not working :(

**Comment by jorijnsmit** [comment]
think we have it going here @poolpitako: https://gnosis-delegator.badger.com/

via https://github.com/Badger-Finance/gnosis-safe-delegate-dapp

**Comment by poolpitako** [comment]
perfect! thanks.

**Comment by poolpitako** [comment]
tx service url changed recently, so I guess that's failing.
For reference:
https://github.com/banteg/ape-safe/pull/36

**Pull request closed without merging**
